spec-version: 0.36.0
name: creditmonad
version: 1.0.0
synopsis: Reasoning about amortized complexity
category: Development
extra-source-files:
  - CHANGELOG.md
  - resources/**/*

ghc-options: -Wall -Wno-name-shadowing -fworker-wrapper-cbv -O2 -threaded -rtsopts

dependencies:
  - base >= 4.13 && < 5
  - containers >= 0.6 && < 1.7
  - mtl >= 2.3 && < 2.4
  - prettyprinter >= 1.7 && < 1.8
  - QuickCheck >= 2.14 && < 3
  - STMonadTrans >= 0.4 && < 0.5

language: GHC2021

library:
  source-dirs: src
  exposed-modules:
    - Control.Monad.Credit
    - Test.Credit
    - Test.Credit.Deque.Bankers
    - Test.Credit.Deque.Base
    - Test.Credit.Deque.Catenable
    - Test.Credit.Deque.ImplicitCat
    - Test.Credit.Deque.Realtime
    - Test.Credit.Deque.SimpleCat
    - Test.Credit.Deque.Streams
    - Test.Credit.Finger
    - Test.Credit.Heap.Base
    - Test.Credit.Heap.Binomial
    - Test.Credit.Heap.LazyPairing
    - Test.Credit.Heap.Pairing
    - Test.Credit.Heap.Scheduled
    - Test.Credit.Queue.Bankers
    - Test.Credit.Queue.Base
    - Test.Credit.Queue.Batched
    - Test.Credit.Queue.Bootstrapped
    - Test.Credit.Queue.Implicit
    - Test.Credit.Queue.Physicists
    - Test.Credit.Queue.Realtime
    - Test.Credit.Queue.Streams
    - Test.Credit.RandomAccess.Base
    - Test.Credit.RandomAccess.Binary
    - Test.Credit.RandomAccess.Zeroless
    - Test.Credit.Sortable.Base
    - Test.Credit.Sortable.MergeSort
    - Test.Credit.Sortable.Scheduled
  other-modules:
    - Control.Monad.Credit.Base
    - Control.Monad.Credit.CreditM
    - Control.Monad.Credit.CounterM

executable:
  main: Main.hs
  source-dirs: app
  dependencies:
    - creditmonad
    - unliftio >= 0.2 && < 0.3